/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bank.h"

int get_account_index_by_cpf(int cpf) 
{
	int i = 0;
	for( i; i < NUM_OF_ACCOUNTS; i++)
	{
		if( Contas[i].cpf == cpf )
		{
			return i;
		}
	}
	printf("CPF nao encontrado!\n");
	return -1;
}

int get_last_available_index( ) 
{
	int i = 0;
	for( i; i < NUM_OF_ACCOUNTS; i++)
	{
		if (Contas[i].cpf == 0)
		{
			return i;
		}
	}
	printf("Lista de clientes cheia!\n");
	return -1;

}


bool_t *
abertura_100_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */
	int cpf = *argp;

	if( get_account_index_by_cpf( cpf ) != -1 )
	{
		result = 0;
		return &result;
	}

	int lastIndex = get_last_available_index();
	if( lastIndex == -1 )
	{
		result = 0;
		return &result;
	}

	Conta newAccount;

	newAccount.cpf = cpf;
	newAccount.saldo = 0;
	newAccount.transactionCount = 1;

	Contas[lastIndex] = newAccount;

	result = 1;
	return &result;
}

bool_t *
fechamento_100_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	int cpf = *argp;
	int index = get_account_index_by_cpf( cpf );
	if( index == -1 )
	{
		result = 0;
		return &result;
	}

	memset(&Contas[index], 0, sizeof( Conta ) );

	result = 1;
	return &result;
}

int *
autentica_100_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int cpf = *argp;

	printf("Autenticando cpf: %d\n", cpf);
	int index = get_account_index_by_cpf( cpf );
	if( index == -1 )
	{
		result = -1;
		return &result;
	}

	result = Contas[index].transactionCount;
	return &result;
}

bool_t *
transacao_100_svc(TransactionInfo *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */
	int cpf = argp->cpf;
	int index = get_account_index_by_cpf( cpf );
	if( index == -1 )
	{
		result = 0;
		return &result;
	}

	if( argp->transactionCount != Contas[index].transactionCount + 1 )
	{
		result = 0;
		printf("Operacao repetida, cancelando operacao\n");
		return &result;
	}

	if( argp->operation == 0 )
	{
		Contas[index].saldo = Contas[index].saldo - argp->valor;
		printf("Retirando\n");
	}
	else
	{
		Contas[index].saldo = Contas[index].saldo + argp->valor;
		printf("Depositando\n");
	}
	
	Contas[index].transactionCount++;
	
	result = 1;
	return &result;
}

int *
consulta_100_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int cpf = *argp;
	int index = get_account_index_by_cpf( cpf );
	if( index == -1 )
	{
		result = -1;
		return &result;
	}

	result = Contas[index].saldo;

	return &result;
}