/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bank.h"


void
bank_100(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	int  abertura_100_arg;
	bool_t  *result_2;
	int  fechamento_100_arg;
	bool_t  *result_3;
	int  autentica_100_arg;
	bool_t  *result_4;
	TransactionInfo  transacao_100_arg;
	int  *result_5;
	int  consulta_100_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BANK, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = abertura_100(&abertura_100_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = fechamento_100(&fechamento_100_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = autentica_100(&autentica_100_arg, clnt);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = transacao_100(&transacao_100_arg, clnt);
	if (result_4 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = consulta_100(&consulta_100_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bank_100 (host);
exit (0);
}
